### ISSUE TITLE
Remove "{" in fieldValueList to get Sequences for new Version

### ISSUE THREAD

**Issue by Rivarsal** [corunet/kloadgen#179]
Remove the necessity of using "{" in the fieldValueList in order to get a Sequence.

**Comment by t-h-e** [comment]
As far as I understand, currently the field type `seq` can be used in two different ways.
Either *with* `{` and a field value list, e.g. `[{5,3,4]`, which will then use the values in the following order `5->3->4->5->...`
Or *without* `{` and then the first value of the field value list will be used to generate a sequence (probably only works with numbers?). E.g. field value list `[5,3,4]`, with result in `5->6->7->...`

Is it planned to still support the first case?

**Comment by jemacineiras** [comment]
HI @t-h-e,
The plan is to remove the '{' and  make de behaviour more consistent using only the `seq`. Meaning that if you provide a list of values, you will get a sequence on that list only, like the `[5,3,4]` example. In case only one value be provided, this will work as initial value like the behaviour you relate _without_ `{`.
I just saw you PR, thanks!!
Only a comment, in order to keep track of the changes we like to have an issue linked to the PR, if you don't mind. We are still working in the documentation and collaboration rules.

Cheers

**Comment by t-h-e** [comment]
Hi @jemacineiras,
thanks for the nice plugin. 😃 
Sure no problem. I created an issue for my PR.

One question about removing `{` though.
How to distinguish between the two cases, if only a single element is given?
Currently:
`[{1]` will result in `1->1->...`
`[1]` will result in `1->2->3->...`
Afterwards only the second case is possible. To allow the first case, one has to write `[1,1]`, right?
IMHO, this does not feel intuitive and may lead to people opening unnecessary issues. Would it be more explicit to use two different field types, like `seq` and `fieldlist` (or whatever)?

**Comment by jemacineiras** [comment]
Hi @t-h-e,

your first case is wrong, If you want always to be `1`, you don't specify a `seq`, just only the type of, like _integer_, _long_....
You will only set type to `seq` when you need a sequence for that specific field.

If a list of elements is provided, then we will iterate over it and use as a `valid set` to get the values.
I’m trying to keep the things as easy as I can, just to be prepared in case in the future we want to add some way to specify a number sequence with a predefined hop (like +2 or +0.5 instead of +1) O:)

Cheers
