### ISSUE TITLE
[Issue]: parametrization is not working on protobuf

### ISSUE THREAD

**Issue by nrellanti** [corunet/kloadgen#243]
### What happened?

Parameterization is not working on Schema File Load Generator Config 
[occurrence.zip](https://github.com/corunet/kloadgen/files/8642956/occurrence.zip)

### KloadGen Version

Kloadgen-4.0.8

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by irodigl** [comment]
Hi @nrellanti!

Thank you for your collaboration, we will review the problem and we will inform you as soon as posible.

**Comment by irodigl** [comment]
Hi @nrellanti,

I´m seeing you are try to use a variable from the csv? you should writed as JMeter variable in the way ${ ...... }

In the other hand, we saw that you are using these types: Stringvalue, Int32Value... We are considering them as an Object so if you try to use them because of the null allowance, we have our proper way to define null values. You can check this section: https://github.com/corunet/kloadgen/wiki#null-values

Thanks you for the support :)

See ya!

**Comment by nrellanti** [comment]
Thank you @irodigl .
We will implement your suggestions on our proto file, and get back to you if any further information require

**Comment by irodigl** [comment]
Hi @nrellanti,

We will review the question that you are proposing us for giving you feedback as quickly as possible.

Thank you a lot!

See ya! :)

**Comment by nrellanti** [comment]
Thank you @irodigl !

**Comment by irodigl** [comment]
Hi @nrellanti,

we've been investigating about the issue and we have detected the error in code. So now, we are going to create a branch for solving it and I will notify you for you can testing your solution.

Thanks again!! :)

**Comment by nrellanti** [comment]
Thank you @irodigl

**Comment by nrellanti** [comment]
@irodigl , #243_parametrization_protobuf, branch tested and verified. Working as expected for all the parametrization values.
Thank you very much!
