### ISSUE TITLE
Producer properties : message.key.value to be unique for each loop

### ISSUE THREAD

**Issue by vcbkarthi** [corunet/kloadgen#65]
HI 

there is a scenarios to use unique message key value for each iteration of the loop . but even if i use a time function for example 
${__threadNum}_${__time(ddMMyyyyHHMMSS)} like this it always takes the first value as message key for the next iteration also .

but i need this to change , is there a way to achieve this ?

**Comment by kszosze** [comment]
HI @vcbkarthi,
we will take a look into it soon.
Can you please upload a test plan with that scenario please?
Cheers!!

**Comment by vcbkarthi** [comment]
[sampleKafka.zip](https://github.com/corunet/kloadgen/files/5511112/sampleKafka.zip)

attaching the sample

**Comment by vcbkarthi** [comment]
i have changed the thread group to arrival thread group so  that , every iteration becomes a new thread , this has solved the issue , but it could be helpfull if the iterations can create a new unique message in the message key

**Comment by kszosze** [comment]
As it works, we recover the variables JMeter from the context and replace the placeholders you put into the "message.key.value" every time a message is created and send. In order to generate different values you need to generate them in a thread group or in a loop controller, but adding to the context variables.
Seeing your expression, I can see you added the functions into the request configuration, that means they are evaluated by JMeter runner when create the thread at the start and what we got in the sampler is always in each iteration.
My advice is try to generate the values in a Pre-processor and pass the variable in "message.key.value" expression.
Can you try that? There is a variable substitution example jmx in the root folder.
Cheers

**Comment by kszosze** [comment]
Hi @vcbkarthi,
Any luck with my latest comment.
Regards!!

**Comment by kszosze** [comment]
"i have changed the thread group to arrival thread group so that , every iteration becomes a new thread , this has solved the issue , but it could be helpfull if the iterations can create a new unique message in the message key"
I think we have a tiny hole in our documentation, if you specify a type in "message.key.value" like string, int, uuid... it will generate random values of this type. We will update the documentation accordly to this feature.
Cheers

**Comment by kszosze** [comment]
Hi @vcbkarthi,
Any luck with my latest comment.
Regards!!

**Comment by codigoFuentes** [comment]
Closed by inactivity
